vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profilepicture_image:
            uri_prefix: '%profilepicture_image%'
            upload_destination: '%kernel.project_dir%/public%profilepicture_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
