vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profilepicture_images:
            uri_prefix: '%app.path.profilepicture_images'
            upload_destination: '%kernel.project_dir%/public%app.path.profilepicture_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
