vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profilepicture_image:
            uri_prefix: '%app.path.profilepicture_image'
            upload_destination: '%kernel.project_dir%/public%app.path.profilepicture_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
